version: '3.5'
networks:
  public:
    external: true
volumes:
  voldata:
  volgroups:
  volrecordings:
services:
  galene:
    image: sebt3/galene:latest
    command: -insecure
    volumes:
      - voldata:/data
      - volgroups:/groups
      - volrecordings:/recordings
    networks:
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.galene.loadbalancer.server.port=8443
        - traefik.http.routers.galene.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.galene.entrypoints=web
